# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sbomify
description: >- # this means to ignore newlines until "baseurl:"
  Sbomify.com streamlines SBOM exchange for businesses. Our platform supports customers, vendors, and ISVs in sharing SBOMs efficiently—ideal for transactions, compliance, and mergers. Enhance trust and clarity in your software supply chain with transparent and effective SBOM management. Join us to revolutionize SBOM sharing and management.

# the subpath of your site, e.g. /blog
baseurl: ""

# the base hostname & protocol for your site
url: "https://sbomify.com"

social:
  image: "/assets/images/site/sbomify.png"
  profiles:
    - platform: "X"
      url: "https://x.com/sbomify"
      handle: "sbomify"
    - platform: "LinkedIn"
      url: "https://www.linkedin.com/company/sbomify/"

pagination:
  enabled: true

permalink: /:year/:month/:day/:title/

sass:
  style: compressed
  sourcemap: never

google_analytics: G-4DYDPF55FX


# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jekyll-minifier

jekyll-minifier:
  uglifier_args:
    harmony: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - Dockerfile

feed:
  path: feed.xml
  posts_limit: 20
  excerpt_only: false
  categories:
    - compliance
    - security
    - sbom
