---
services:
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm run watch:css & bundle exec jekyll serve --config _config.yml,_config_development.yml"
